version: "3.7"
services:
  xhttp:
    container_name: xhttp
    #user: xphp
    build: ./xhttp/php/5.6.40-fpm
    image: xhttp:latest
    depends_on:
      - xloadbalancer
    ports:
      - target: 8443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - xnetwork
    environment:
      - MY_XHTTP_VAR=MyXhttpVar
  xloadbalancer:
    container_name: xloadbalancer
    #user: xwww-data
    build: ./xloadbalancer/httpd/2.4.41-alpine
    image: xloadbalancer:latest
    ports:
      - target: "80"
        published: "80"
        protocol: tcp
        mode: host
      - target: "443"
        published: "443"
        protocol: tcp
        mode: host
    networks:
      - xoutside
      - xnetwork

networks:
  xoutside:
    external:
      name: xoutside
  xnetwork:
    name: xnetwork